name: detto
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shared_preferences: ^2.0.10
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.1.1
  flutter:
    sdk: flutter
  open_file: ^3.2.1
  path_provider: ^2.0.14
  image_picker: ^0.8.4+3
  pdf: ^3.4.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  video_player: ^2.4.0
  chewie: ^1.0.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
<<<<<<< HEAD
      - assets/images/fotografia.png
      - assets/images/codigoqr.png
      - assets/images/Detto.mp4
      - assets/images/detto.png
      - assets/images/cli1.png
      - assets/images/cli2.png
      - assets/images/cli3.png
      - assets/images/cli4.png
      - assets/images/cli5.png
      - assets/images/cli6.png
      - assets/images/cli7.png
      - assets/images/cli8.png
  #   - images/a_dot_ham.jpeg
=======
    - assets/images/fotografia.png
    - assets/images/codigoqr.png
    - assets/images/Detto.mp4
    - assets/images/detto.png
  fonts:
    - family: detto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
>>>>>>> bb1cb1d45ed61b98b74875ad9d745d27ab99b49e

